### ISSUE TITLE
When I enter a script tag in my Markdown spec file, the footer gets repeated. A totally weird bug.

### ISSUE THREAD

**Issue by mik01aj** [sourcejs/Source#156] opened 2015-06-19 15:38 UTC
And this happens *before* my js file is executed. I mean, even if I set a breakpoint on the 1st line, the breakpoint is hit when the footer is already duplicated. I have no idea what is causing this. This is somewhat related with my JS (because when loading it fails, this error doesn't happen).

It looks like this:
![screenshot 2015-06-19 17 20 44](https://cloud.githubusercontent.com/assets/3027415/8256809/af078a72-16a9-11e5-811a-035c9e266197.png)

Notice the version number in the footer. Maybe this will give you some hint. Thank you in advance! :)

**Comment by mik01aj** [comment] 2015-06-22 14:50
Looks like this has something to do with RequireJS. My Markdown had just the script tag, and the script was a bundle built using Browserify with the `standalone` option, which wraps all code in [UMD](https://github.com/umdjs/umd). And this UMD looks for module system, finds RequireJS, tries to define an asynchronous module, and somehow fails.

I realize that my question could have been more general: How do I include my custom javascript on the spec page?

**Comment by operatino** [comment] 2015-06-22 19:40
Thanks for the bug report, I also noticed it few times before, but could reproduce it after. Could you please provide a bit more details about the code? I would like to investigate it and fix ASAP in 0.5.4.

> I realize that my question could have been more general: How do I include my custom javascript on the spec page?

You can link it directly to spec file (`readme.md`, `index.src.html`), or into parent `.ejs` template, which is especially useful if you need to link same files to few specs. 

But in some edge cases, you JS code could have conflicts with SourceJS UI. We are aware of it, and it's actually a top priority for upcoming 0.6 release, where we will totally isolate engine's JS. 

It's also already possible to create a plugin, which will wrap all the examples in Shadow DOM.

**Comment by operatino** [comment] 2015-06-24 08:05
I'm trying to reproduce it, but still with no luck. I can assume it's an issue with broken HTML coming from markdown, will try to investigate it deeper.

**Comment by mik01aj** [comment] 2015-06-25 15:29
The HTML coming from the server is correct, I checked it. There is something strange happening on the client side.

**Comment by operatino** [comment] 2015-06-29 08:30
I desperately try to reproduce it, but I can't. Could you please try to debug this JS file `sourcejs/assets/js/modules/headerFooter.js`?

It checks if header or footer already exists and injects it on client-side. This is left for legacy support of `index.html` specs. Later I will leave only server-side injection.

**Comment by operatino** [comment] 2015-07-10 11:54
Could you please check it again in latest `0.5.4-dev` branch? I replaced JSDom with Cheerio, it could solve this strange issue.

**Comment by operatino** [comment] 2015-08-10 20:38
I will close this issue for now, since I expect it should be fixed after removing JSDom from spec rendering.

**Closed by operatino** 2015-08-10 20:38 UTC
Labels: bug, help wanted

**Comment by operatino** [comment] 2015-11-15 20:47
I finally managed to reproduce it, and fixed it.
